on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: daianearrudaa
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -m "Update snake animation"
          git push https://$GH_TOKEN@github.com/daianearrudaa/daianearrudaa.git HEAD:output

